### ISSUE TITLE
Random crash when built and run under Alpine linux

### ISSUE THREAD

**Issue by twarit-waikar** [salesforce/p4-fusion#56]
The error seems to only occur in the musl library, and doesn't mention any p4-fusion specific functions in the stacktrace, even in a debug build. However, we only see this in alpine builds.

p4-fusion crashes in this case either at the end of the execution, or before starting the Git commit process (or when the tool is downloading files)

GDB core dump below:

```
Core was generated by `p4-fusion --path //depot/path/... --client p4-client'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5bd160c896 in ?? () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 296)]
(gdb) where
#0  0x00007f5bd160c896 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007f5bd160cc2f in ?? () from /lib/ld-musl-x86_64.so.1
#2  0x0000000000000000 in ?? ()
```

**Comment by Strum355** [comment]
Fwiw we're statically linking with musl and not getting segfaults that Im aware of
